config/routes.rb
Rails.application.routes.draw do
 
  resources :requests
  devise_for :users
  root to: 'shops#index'
  resources :shops
  match 'sale', to: 'shops#sale', via: [:get]
  get '/search' => 'shops#search', :as => 'search_page'
  match 'newrequest', to: 'requests#newrequest', via: [:get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :user
	validates_presence_of :user
end

app/models/shop.rb
class Shop < ApplicationRecord
	has_many_attached :images
	validates :title, presence: true
	validates :description, presence: true
	validate :image_type
	validates :excost, presence: true
	belongs_to :user
	validates_presence_of :user
	

	def thumbnail input
		return self.images[input].variant(resize: '300x300!').processed
	end

	private
	def image_type
		if images.attached? == false
			errors.add(:images, "are missing!")	
		end
		images.each do |image|
			if !image.content_type.in?(%('image/jpeg image/png'))
				errors.add(:images, 'needs to be a JPEG or PNG')
			end	
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shops
  has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /requests
  # GET /requests.json
  def index
   @requests = Request.where.not(:user_id => current_user.id)
  end

  def newrequest
    @requests = Request.where(:user_id => current_user.id)
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end



  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.user_id = current_user.id
    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to newrequest_path, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:description, :category, :contactdetails)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.where(:user_id => current_user.id)
  end

  def sale
    @shops = Shop.where.not(:user_id => current_user.id)
  end

  def search 
   if params[:search].blank?  
    redirect_to(root_path, alert: "Empty field!") and return  
  else  
    @parameter = params[:search].downcase  
    @results = Shop.all.where("lower(category) LIKE :search", search: @parameter)  
  end   
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:title, :description, :excost, :category, :contact, :address, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SHOPPING APP</title>
   <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "NITK Shopping App", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path , class: "btn "%></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path, class: "btn "  %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "btn " %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description,:required => true, minlength:20,maxlength:250 %>
  </div>

  <div class="field">
    <p>Enter Category only one word for better Searches (Ex :- book,cycle,laptop)</p>
    <%= form.label :category %>
    <%= form.text_field :category,:required => true %>
  </div>


  <div class="field">
    <p>Contact Details (Ex :- name,mobile,address)</p>
    <%= form.label :Contact_Details %>
    <%= form.text_field :contactdetails,:required => true,minlength:15,max_Dength:250 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', newrequest_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.description %></td>
        <td><%= request.category %></td>
        <td><%= link_to 'Show', request %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', newrequest_path %>

app/views/requests/newrequest.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.description %></td>
        <td><%= request.category %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Got the Item', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %> |
<%= link_to 'Back', root_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @request.category %>
</p>
<p>
  <strong>Contact Details:</strong>
  <%= @request.contactdetails %>
</p>

<% if current_user.id == @request.user_id %>
<%= link_to 'Edit', edit_request_path(@request) %> |
<% end %>

<% if current_user.id == @request.user_id %>
<%= link_to 'Back', newrequest_path%> 
<% else %>
<%= link_to 'Back', requests_path%>
<% end %>

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title,:required => true, minlength:10,maxlength:40 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description,:required => true, minlength:20,maxlength:250 %>
  </div>
   <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images,multiple: true %>
  </div>

  <div class="field">
    <%= form.label :excost %>
    <%= form.number_field :excost,:required => true %>
  </div>

   <div class="field">
    <p>Enter Category only one word for better Searches (Ex :- book,cycle,laptop)</p>
    <%= form.label :category %>
    <%= form.text_field :category,:required => true %>
  </div>

   <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact,:required => true, minlength:10,maxlength:10 %>
  </div>

   <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address,:required => true, minlength:15,maxlength:250 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>
 <%= link_to 'Go To Things On Sale', sale_path %>
 <br>
 <%= link_to 'Requests', requests_path %>
 <br>
  <%= link_to 'Manage Your Requests', newrequest_path %>
  <br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Category</th>
      <th scope="col">Excost</th>
      <th scope="col"></th>
    </tr>
  </thead>


    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.title %></td>
        <td><%= shop.category %></td>
        <td><%= shop.excost %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Sold Out', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/sale.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>
<h1>Shops</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
     
      <th scope="col">Category</th>
      <th scope="col">Excost</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.title %></td>
               <td><%= shop.category %></td>
        <td><%= shop.excost %></td>
        <td><%= link_to 'Show', shop %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Back', shops_path %>

app/views/shops/search.html.erb
<h1>Shops</h1>

<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Excost</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |shop| %>
      <tr>
        <td><%= shop.title %></td>
        <td><%= shop.description %></td>
        <td><%= shop.category %></td>
        <td><%= shop.excost %></td>
        <td><%= link_to 'Show', shop %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', sale_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shop.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>
<p>
  <strong>Images:</strong>
<ul class="bxslider">
  <% (0...@shop.images.count).each do |image| %>

  <li> <%= image_tag(@shop.thumbnail(image))%></li>
   
   <% end %>
 </ul>

</p>

<p>
  <strong>Excost:</strong>
  <%= @shop.excost %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shop.category %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @shop.contact %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>


<% if current_user.id == @shop.user_id %>
<%= link_to 'Edit', edit_shop_path(@shop) %> |
<% end %>



<% if current_user.id == @shop.user_id %>
<%= link_to 'Back', root_path%> 
<% else %>
<%= link_to 'Back', sale_path%>
<% end %>